[pytest]
python_files = test_*.py
norecursedirs =
    .git
    .pytest_cache
    .venv
    __pycache__
    node_modules
    target
    dist
    build
    desktop
    data
    tmp
    PDF_MD_lib
    __MACOSX
addopts = -ra
